# Activate/Deactivate flags
flag_IBS: 1                 # If 1 calculate with IBS
flag_SR: 0                  # If 1 calculate with SR

ibs_lib_path: "./"

#duration: 1 #0.001425986        # Duration in seconds
duration: 7200        # Duration in seconds
ibs_step: 300 #0.001 #1.4259865297332022e-05                # time step

# Sequence to load
sequence: "../lines_and_sequences/top_protons/run3_top.seq" 
sequence_name: 'lhcb1'

energy: 6800.0                           # energy in GeV
bunch_intensity: 1.8e11
emit_x: 1.8
emit_y: 1.8                         # ey in um
blns: 1.2 
bl_lev: 0.0                  
particle: "proton"
mass: 0.9382723
radius: 1.534698e-18
charge: 1

V0max: 12                       # RF voltage in MV
h: 35640
cc_name_knobs: "vrf400"

# Save results
save_to: ./IBS_output.parquet
